# Generated by Django 3.2.4 on 2023-02-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=23)),
                ('edad', models.PositiveIntegerField()),
                ('profesion', models.CharField(max_length=45)),
            ],
        ),
    ]
